StoreCrafter/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :customers do
    resources :services do
      collection do
        get 'service_reopened'
        post 'service_reopened'
      end

      resources :component_associations
    end
  end
  resources :service_components
  get 'services/index'
end

StoreCrafter/app/models/service.rb
class Service < ApplicationRecord
  belongs_to :customer
  has_many :checklist_associations
  has_many :service_checklists , through: :checklist_associations
  has_many :component_associations
  has_many :service_components , through: :component_associations
  validates :product_name ,presence: true
  validates :datetime ,presence: true
  validates :requested_delivery ,presence: true
  validates :cost ,presence: true
  validates :quantity ,presence: true
  validates :problem_statement ,presence: true

  enum status: { pending:0 , analyzing: 1 , servicing: 2 ,payment_pending: 3 ,delivered: 4 }
  enum reopen: { first_time:0,second_time:1,third_time:2,fourth_time:3}
 end

StoreCrafter/app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
     @service={}
     @checklist_association = {}
    Service.statuses.keys.each do |status|
      @service[status.to_s] = Service.where(status: status) 
    end
    Service.all.each do |service|
      @checklist_association[service.id] = []
      for i in 0..service.reopened
        
        # @checklist_association[service.id] = { i => ChecklistAssociation.where(service_id: service.id,reopened: i).pluck(:service_checklist_id)}
        @checklist_association[service.id].push(ChecklistAssociation.where(service_id: service.id,reopened: i).pluck(:service_checklist_id))
        # debugger
      end
      
     end
     debugger
    @checklist = ServiceChecklist.pluck(:id , :checklist_name)
    @service
    @checklist_association
  
  end
  def new
    @customer = Customer.find(params[:customer_id])
    @service = @customer.services.new
  end
  def show
    @customer = Customer.find(params[:customer_id])
    # debugger
    @service  = @customer.services.find(params[:id])
  end
  def create
    @customer = Customer.find(params[:customer_id])
    @service = @customer.services.create(service_params)
    @service.update(status:0,reopened:0)
    @checklist = @service.checklist_associations.new
    @checklist.service_checklist_id = 1
    debugger
    @checklist.reopened = 0
    @checklist.save

      redirect_to '/services/index'
  end
  def edit
    @customer = Customer.find(params[:customer_id])
    @service = @customer.services.find(params[:id])
  end
  def update
    # debugger
    @customer = Customer.find(params[:customer_id])
    @service = @customer.services.find(params[:id])

    @service_params = params[:service]
    # debugger
    @servicechecklistids = @service.checklist_associations.all.where(:reopened=>@service.reopened).pluck(:service_checklist_id)
    for i in 6..@service_params.keys.size-1
      # debugger
      if ((@service_params.values[i] == "1")&&((@servicechecklistids.include? @service_params.keys[i].to_i) == false))
        @checklist = @service.checklist_associations.new
        @checklist.service_checklist_id = @service_params.keys[i]
        @checklist.reopened = @service.reopened
        @checklist.save
      elsif ((@service_params.values[i] == "0")&&((@servicechecklistids.include? @service_params.keys[i].to_i) == true))
        # debugger
        @deleteassociations = @service.checklist_associations.all.where(:reopened=>@service.reopened,:service_checklist_id=>@service_params.keys[i]).ids
        ChecklistAssociation.delete(@deleteassociations)
      end
    end
    @service = @customer.services.find(params[:id])
    @updatestatus = @service.checklist_associations.all.where(:reopened=>@service.reopened).pluck(:service_checklist_id)
    debugger
    if ((@updatestatus.size == 2)&&(@updatestatus.last == 2))
      @service.update(status:1)
    elsif(@updatestatus.size == 1)
      @service.update(status:0)
    elsif(@updatestatus.size == 0)
      @service.update(status:0)
    elsif((@updatestatus.size == 3)&&(@updatestatus.last == 3))
      @service.update(status:2)
    elsif((@updatestatus.size == 4)&&(@updatestatus.last == 4))
      @service.update(status:2)
    elsif((@updatestatus.size == 4)&&(@updatestatus.last == 4))
      @service.update(status:2)
    elsif((@updatestatus.size == 5)&&(@updatestatus.last == 5))
      @service.update(status:2)
    elsif((@updatestatus.size == 6)&&(@updatestatus.last == 6))
      @service.update(status:2)
    elsif((@updatestatus.size == 3)&&(@updatestatus.last == 7))
      @service.update(status:3)
    elsif((@updatestatus.size == 7)&&(@updatestatus.last == 7))
      @service.update(status:3)
    elsif((@updatestatus.size == 8)&&(@updatestatus.last == 8))
      @service.update(status:4)
    elsif((@updatestatus.size == 9)&&(@updatestatus.last == 9))
      @service.update(status:4)
    elsif((@updatestatus.size == 9)&&(@updatestatus.include? 9))
      @service.update(status:4)
    end
    # @customer = Customer.find(params[:customer_id])
    if @service.update(service_params)
        redirect_to '/services/index'
      end
  end
  def destroy
    @customer = Customer.find(params[:customer_id])
    @service = @customer.services.find(params[:id])
    @service.checklist_associations.destroy_all
    if @service.destroyed?
      @service.destroy
      redirect_to @customer
    end
  end
  def service_reopened
    @service = Service.find(params[:service_id])
    @service.reopened=@service.reopened+1
    @service.status=0
    @service.checklist_associations.new.service_checklist_id = 1
    if @service.save
        redirect_to '/services/index'
    end
  end
  private
  def service_params
    params.require(:service).permit(:product_name, :datetime, :requested_delivery, :problem_statement, :quantity, :cost, :status, :checklist ,:reopen )
  end
end

StoreCrafter/app/helpers/services_helper.rb
module ServicesHelper
end

StoreCrafter/app/views/services/edit.html.erb
<%= form_with(model: @service,url:customer_service_path,method: :put, local: true ) do |form| %>
  <p>
    <%= form.label :product_name %>
    <%= form.text_field :product_name %>
  </p>
  <p>
    <%= form.label :datetime %>
    <%= form.text_field :datetime %>
  </p>
  <p>
    <%= form.label :requested_delivery %>
    <%= form.text_field :requested_delivery %>
  </p>
  <p>
    <%= form.label :problem_statement %>
    <%= form.text_field :problem_statement %>
  </p>
  <p>
    <%= form.label :quantity %>
    <%= form.text_field :quantity %>
  </p>
<!--  <p>-->
    <%#= form.label :status %>
    <%#= form.text_field :status %>
<!--  </p>-->
  <p>
    <%= form.label :cost %>
    <%= form.text_field :cost %>
  </p>

  <%= form.submit %>
<% end %>

StoreCrafter/app/views/services/index.html.erb
<! DOCTYPE html>
<html>
<head>
</head>
<body id="servicebody">
<header>
  <h3></h3>
StoreCrafter
</header>
<div id="container"></div>
<div class="container-fluid" >
  <div class="row">
    <%= react_component("HelloWorld" , {services: @service , statuses: Service.statuses , checklist:@checklist , checklist_association: @checklist_association}) %>
      <% @service = Service.all %>
      <% Service.statuses.each do |status| %>
      <div class="col-xs-2 col-half-offset " id="stylo">
          <h3 style="text-align: left"><%= status[0].split("_").join(" ").upcase_first %></h3>
          <% @service.each do |service| %>
            <% if service.status == status[0] %>
            <%= link_to customer_service_path(service.customer_id,service.id) ,:id=>"card-main",:class => "btn btn-default"  do%>
                <div >
                  <h4><% if ((service.reopened) >= 1) %>
                      <span class="glyphicon glyphicon-registration-mark" id="R"><%= service.reopened %></span>
                    <% end %>
                    <%= service.product_name %>
                  </h4>

                  <div class="instance-card">
                  <h6>Status: <%= ServiceChecklist.find(service.service_checklist_ids.last).checklist_name.split("_").join(" ").upcase_first %></h6>
                  <h5 id="checklist" class="glyphicon glyphicon-check badge is-complete ">
                    <%= service.checklist_associations.all.where(:reopened=>service.reopened).size %>/<%= ServiceChecklist.all.size%>
                  </h5>
                  </div>
                </div>
            <% end %>
             <%end %>
      <% end %>
          <%= link_to 'Add new Service' ,customers_path,:class=>"btn btn-default",:id=>'newservice'%>
      </div>
      <% end %>
    <div class="col-xs-2 col-half-offset " id="stylo">
      <h3 style="text-align: left">Reopened</h3>
      <% @service.each do |service| %>
        <% if ((service.checklist_associations.all.where(:reopened=>service.reopened).ids.size == 0) && (service.checklist_associations.all.where(:reopened=>service.reopened).pluck(:service_checklist_id).size == 0))%>
          <%= link_to customer_service_path(service.customer_id,service.id) ,:id=>"card-main",:class => "btn btn-default"  do%>
            <div >
              <h4><% if (service.reopened >=1 ) %>
              <span class="glyphicon glyphicon-registration-mark" id="R"><%= service.reopened %></span><%end %>
                <%= service.product_name %></h4>
              <div class="instance-card">
                <h6>Status: Reopened</h6>
                <h5 id="checklist" class="glyphicon glyphicon-check badge is-complete ">
                  <%= service.service_checklist_ids.size %>/<%= ServiceChecklist.all.size%>
                </h5>
              </div>
            </div>
          <% end %>
        <%end %>
      <% end %>
      <%= link_to 'Add new Service' ,customers_path,:class=>"btn btn-default",:id=>'newservice'%>
    </div>
  </div>
</div>


</body>
</html>

StoreCrafter/app/views/services/new.html.erb
<%= form_with(model: [ @customer , @customer.services.build ] ,url:customer_services_path, local: true ) do |form| %>
  <p>
    <%= form.label :product_name %>
    <%= form.text_field :product_name %>
  </p>
  <p>
    <%= form.label :datetime %>
    <%= form.text_field :datetime %>
  </p>
  <p>
    <%= form.label :requested_delivery %>
    <%= form.text_field :requested_delivery %>
  </p>
  <p>
    <%= form.label :problem_statement %>
    <%= form.text_field :problem_statement %>
  </p>
  <p>
    <%= form.label :quantity %>
    <%= form.text_field :quantity %>
  </p>
  <p>
    <%= form.label :cost %>
    <%= form.text_field :cost %>
  </p>
  <%= form.submit %>
<% end %>

StoreCrafter/app/views/services/show.html.erb
<! DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
</head>
<body id="servicebody">
<header>
  <h3></h3>
  StoreCrafter
</header>



<div class="container-fluid" >
  <div class="row" style="padding-bottom: 0;">
<%= form_with(model:[@service],url:customer_service_path,method: :put, local: true ) do |form| %>
  <p>
    <%= form.label :product_name %>
    <%= form.text_field :product_name , :disabled => false%>
  </p>
  <p>
    <%= form.label :datetime %>
    <%= form.text_field :datetime , :disabled => false%>
  </p>
  <p>
    <%= form.label :requested_delivery %>
    <%= form.text_field :requested_delivery , :disabled => false%>
  </p>
  <p>
    <%= form.label :problem_statement %>
    <%= form.text_field :problem_statement , :disabled => false%>
  </p>
  <p>
    <%= form.label :quantity %>
    <%= form.text_field :quantity , :disabled => false%>
  </p>
  <!--  <p>-->
  <%#= form.label :status %>
  <%#= form.text_field :status , :disabled => true%>
  <!--  </p>-->
  <p>
    <%= form.label :cost %>
    <%= form.text_field :cost , :disabled => false%>
  </p>
    <p>

      <% @service_checklist_ids = ServiceChecklist.all.ids %>

      <% for i in 1..ServiceChecklist.all.size %>
        <% @checklist = @service.checklist_associations.all.where(:reopened=>@service.reopened).pluck(:service_checklist_id) %>
        <% if @checklist.include? @service_checklist_ids[i-1]%>
          <%= form.label ServiceChecklist.find(@service_checklist_ids[i-1]).checklist_name %>
          <%# debugger %>
          <%= form.check_box i , {checked: true , disabled: (ServiceChecklist.find(@service_checklist_ids[i-1]).checklist_name == ServiceChecklist.all[0].checklist_name) } %><br>
        <% else %>
          <%= form.label ServiceChecklist.find(@service_checklist_ids[i-1]).checklist_name %>
          <%= form.check_box @service_checklist_ids[i-1] %><br>
        <% end %>
      <% end %>
      <h3>Case History</h3>
    <% for j in 0..@service.reopened-1 %>
        <h4 style="background-color: #F7F7F7"><%= j+1 %>th History</h4>
        <% if j<=@service.reopened-1 %>
        <% for i in 1..ServiceChecklist.all.size %>
          <% @checklist = @service.checklist_associations.all.where(:reopened=>j).pluck(:service_checklist_id) %>
          <% if @checklist.include? @service_checklist_ids[i-1]%>
            <%= form.label ServiceChecklist.find(@service_checklist_ids[i-1]).checklist_name %>
            <%# debugger %>
            <%= form.check_box i , {checked: true , disabled: j!=@service.reopened} %><br>
          <% else %>
            <%= form.label ServiceChecklist.find(@service_checklist_ids[i-1]).checklist_name %>
            <%= form.check_box @service_checklist_ids[i-1] %><br>
          <% end %>
        <% end %>
        <%end %>
    <% end %>

  <%# for i in 1..ServiceChecklist.all.size %>
  <%# if @checklist.include? @service_checklist_ids[i-1]%>
  <%#= form.label ServiceChecklist.find(@service_checklist_ids[i-1]).checklist_name %>
<!--          <%#= form.check_box i , {checked: true}%><br>-->
  <%# else %>
        <%#= form.label ServiceChecklist.find(@service_checklist_ids[i-1]).checklist_name %>
<!--          <%#= form.check_box @service_checklist_ids[i-1] %><br>-->
  <%# end %>
  <%# end %>
    </p>
  <p>
  <% if @service.status == "servicing" %>
      <% @service.service_components.each do |components| %>
          <%= components.component_name %>
      <%end  %>

      <%= link_to 'Add component details ?' , new_customer_service_component_association_path(service_id:@service.id) %>
  <%end %>
  </p>
  <p>
    <% if @service.checklist_associations.all.where(:reopened=>@service.reopened).ids.size == ServiceChecklist.all.size %>
        <%= link_to 'Reopen',service_reopened_customer_services_path(service_id:@service.id),:id=>"card-main", :class => "btn btn-default"%>
    <% end %>
  </p>
  <%= form.submit %>
<% end %>
  </div>
</div>
</body>
</html>