StoreCrafter/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :customers do
    resources :services do
      collection do
        get 'service_reopened'
        post 'service_reopened'
      end

      resources :component_associations
    end
  end
  resources :service_components
  get 'services/index'
end

StoreCrafter/app/models/service_component.rb
class ServiceComponent < ApplicationRecord
end

StoreCrafter/app/models/servicecomponent.rb
class Servicecomponent < ApplicationRecord
end

StoreCrafter/app/controllers/service_components_controller.rb
class ServiceComponentsController < ApplicationController
  def index
    @service_component = ServiceComponent.all
  end
  def new
    @service_component = ServiceComponent.new
  end
  def show
    @service_component = ServiceComponent.find(params[:id])
  end
  def create
    debugger
    @service_component = ServiceComponent.new(components_params)
    if @service_component.save
      redirect_to service_components_path
    else
      render 'service_components/new'
    end
  end
  def destroy
    @service_component = ServiceComponent.find(params[:id])
    @service_component.destroy
    redirect_to service_components_path
  end
  def edit
    @service_component = ServiceComponent.find(params[:id])
  end
  def update
    @service_component = ServiceComponent.find(params[:id])
    if @service_component.update(components_params)
      redirect_to service_components_path
  ``else
    render 'service_components/edit'
  ``end
    end
  private
  def components_params
    params.require(:service_component).permit(:component_name, :component_quantity, :component_cost)
  end
end

StoreCrafter/app/helpers/service_components_helper.rb
module ServiceComponentsHelper
end

StoreCrafter/app/views/service_components/edit.html.erb
<%= form_with(model: @service_component , label: true) do |form|  %>
<p><%= form.label :component_name %><br>
<%= form.text_field :component_name%></p>
<p>
<%= form.label :component_quantity %><br>
<%= form.text_field :component_quantity %>
</p>
<p>
  <%= form.label :component_cost %><br>
  <%= form.text_field :component_cost %>
</p>
  <%= form.submit %>
<% end %>

StoreCrafter/app/views/service_components/index.html.erb
<p>
  <h1>List of all Components:</h1>
</p>
<p>
  <% @service_component.each do |component| %>
  <%= component.component_name ? component.component_name : "null" %>
  <%= component.component_quantity ? component.component_quantity : "null"%>
  <%= component.component_cost ? component.component_cost : "null" %>
    <%= link_to 'Destroy' ,service_component_path(component),method: :delete%>
    <%= link_to 'Edit',edit_service_component_path(component) %>
    <br>
  <% end %>
</p>
<p>
  <%= link_to 'Add new Component?', new_service_component_path %>
</p>

StoreCrafter/app/views/service_components/new.html.erb
<%= form_with scope: :service_component, url:service_components_path, local: true do |form| %>
  <p>
    <%= form.label :component_name %>
    <%= form.text_field :component_name %>
  </p>
  <p>
    <%= form.label :component_quantity %>
    <%= form.text_field :component_quantity %>
  </p>
  <p>
    <%= form.label :component_cost %>
    <%= form.text_field :component_cost %>
  </p>
  <%= form.submit %>
<% end %>