StoreCrafter/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :customers do
    resources :services do
      collection do
        get 'service_reopened'
        post 'service_reopened'
      end

      resources :component_associations
    end
  end
  resources :service_components
  get 'services/index'
end

StoreCrafter/app/models/customer.rb
class Customer < ApplicationRecord
  has_many :services
  validates :customer_name, presence: true,
            length:{minimum: 5}
  validates :customer_location, presence: true
  validates :customer_phno,presence: true , uniqueness: true
end

StoreCrafter/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to '/customers'
    else
      render 'new'
    end
  end
  def edit
    @customer = Customer.find(params[:id])
  end
  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to @customer
    else
      render 'customers/index'
    end
  end
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to @customer
  end
  def show
    @customer = Customer.find(params[:id])
  end
  def new
    @customer = Customer.new
  end
  def index
    @customer = Customer.all
  end
  private
  def customer_params
    params.require(:customer).permit(:customer_name, :customer_phno, :customer_location)
  end
end

StoreCrafter/app/helpers/customers_helper.rb
module CustomersHelper
end

StoreCrafter/app/views/customers/edit.html.erb
<%= form_with(model: @customer , label: true) do |form|  %>
<p><%= form.label :customer_name %><br>
<%= form.text_field :customer_name%></p>
<p>
<%= form.label :customer_phno %><br>
<%= form.text_field :customer_phno %>
</p>
<p>
  <%= form.label :customer_location %><br>
  <%= form.text_field :customer_location %>
</p>
  <%= form.submit %>
<% end %>

StoreCrafter/app/views/customers/index.html.erb
<h1>Customers#index</h1>
<p>Find me in app/views/customers/index.html.erb</p>
<p>
  <h1>List of Customer:</h1>
</p>
<p>
  <% @customer.each do |service| %>
  <%= service.customer_name ? service.customer_name : "null" %>
  <%= service.customer_phno ? service.customer_phno : "null"%>
  <%= service.customer_location ? service.customer_location : "null" %>
    <%= link_to 'Show' ,customer_path(service )%>
    <%= link_to 'Destroy' ,customer_path(service),method: :delete%>
    <%= link_to 'Add Services',  new_customer_service_path(service)  %>
    <%= link_to 'Edit',edit_customer_path(service) %>
    <br>
  <% end %>
</p>
<p>
  <%= link_to 'Add new Customer?', new_customer_path %>
</p>

StoreCrafter/app/views/customers/new.html.erb
<% if @customer.errors.any? %>
 <% @customer.errors.full_message.each do |msg|%>
    <li><%= msg %></li><% end %>
<% end %>
<%= form_with scope: :customer, url:customers_path, local: true do |form| %>
  <p>
    <%= form.label :customer_name %>
    <%= form.text_field :customer_name %>
  </p>
  <p>
    <%= form.label :customer_phno %>
    <%= form.text_field :customer_phno %>
  </p>
  <p>
    <%= form.label :customer_location %>
    <%= form.text_field :customer_location %>
  </p>
  <%= form.submit %>
<% end %>

StoreCrafter/app/views/customers/show.html.erb
<p>
  <h1>Customer detail:</h1>
</p>
<p><strong>Name:</strong>
  <%= @customer.customer_name %>
</p>
 <p>
   <strong>Phone Number:</strong>
     <%= @customer.customer_phno %>
 </p>
  <p>
    <strong>Location:</strong>
    <%= @customer.customer_location %>
</p>
<p>
  List of Products under services :
</p>

<p>
  <table>
    <th>Pending</th>
    <% @customer.services.each do |services| %>
    <tr><% if services.status == 'pending' %>

        <td><%= services.product_name %></td>
    </tr>
      <% end %>
    <% end %>
  </table>
</p>

<table>
<p>
  <% @customer.services.each do |services|%>
    <tr>

      <td><%= services.product_name %></td>
      <td><%= services.datetime %></td>
      <td><%= services.requested_delivery %></td>
      <td><%= services.problem_statement %></td>
      <td><%= services.quantity %></td>
      <td><%= services.cost %>
      <td><%= services.status %></td>
      <%# debugger %>
      <td><%= link_to 'Delete',customer_service_path(@customer.id,services.id),
                      method: :delete,
                      data: { confirm: 'R U Sure?'} %></td>
      <td><%= link_to 'Edit',edit_customer_service_path(services.customer_id, services.id ) %></td>
        <br>
    </tr>
  <% end %>
</p>
</table>